### ISSUE TITLE
Null error when a class isn't instantiated

### ISSUE THREAD

**Issue by es50678** [scijava/scijava-jupyter-kernel#101]
I'm not sure if this is an issue with this kernel or groovy. I'm quite new to both java and jupyter notebooks in general. I just noticed this when messing around today:
![image](https://user-images.githubusercontent.com/17823824/111813960-464cec00-88b0-11eb-83f1-e677b949c7fd.png)

If I create a class definition but don't instantiate it in the same cell, this error is thrown. The error goes away when I instantiate the class.

This is quite minor - but just wanted to report it just in case.

**Comment by imagejan** [comment]
@es50678 did you try adding `null` as the last line of your cell? In a notebook, the last expression of the cell is considered the return value that will be in the cell output. Maybe it's causing problems if that value is a `Class`.

(Please note that SciJava and ImageJ2 are now using the BeakerX Groovy kernel instead of this one for their [tutorials](https://github.com/imagej/tutorials), so I don't know how much `scijava-jupyter-kernel` is still going to be developed.)

**Comment by es50678** [comment]
that worked @imagejan! thank you!
