### ISSUE TITLE
[question] Is there any option if conda can't be used

### ISSUE THREAD

**Issue by moovida** [scijava/scijava-jupyter-kernel#102]
Hi, is there a possibility to install this in an environment in which conda can't be installed. Somehow through pip? beakerx has a pip option, so I wonder if there is a way.

Thanks for any insight.

**Comment by ctrueden** [comment]
@moovida The SciJava core team is not really maintaining this kernel anymore, and we are planning to retire it; see [this thread](https://forum.image.sc/t/imagej-jupyter-notebooks-updated-imagej-python-retiring-the-scijava-jupyter-kernel/21845) for details why. But I am interested in any compelling reason that you need to use this kernel over BeakerX's built-in kernels. If there is some reason to continue supporting this kernel, I'm not against it—but we found it very easy to switch all our Java-based notebooks over to the BeakerX Groovy kernel.

As for not using conda: it's been awhile since I worked on this project, but the `dev_install.sh` script just builds the JAR using Maven, then copies the JAR plus dependencies into a single place `opt/scijava-jupyter-kernel`. And then the [conda-forge recipe](https://github.com/conda-forge/scijava-jupyter-kernel-feedstock/blob/6a1d6d5f1fce1863f490e6a58167eaaffd2c5cef/recipe/post-link.sh) just runs some Java code to install it. So the steps to do it manually would be something like:

```shell
# get the code
git clone git://github.com/scijava/scijava-jupyter-kernel
cd scijava-jupyter-kernel

# set the output directory
sjjk_dir=$HOME/jupyter-kernels/scijava-jupyter-kernel
mkdir -p "$sjjk_dir"
sed "s;^sjjk.*;sjjk=$sjjk_dir;"

# build and install the JAR files
sh dev_install.sh

# install the kernel into Jupyter -- adapted from conda-forge recipe's post_link.sh
"${PREFIX}/bin/java" -classpath "$sjjk_dir/*" \
                     "org.scijava.jupyter.commands.InstallScijavaKernel" \
                     -pythonBinaryPath "$(which python)" \
                     -verbose "info" \
                     -classpath "$sjjk_dir/*" \
                     -javaBinaryPath "$(which java)"
```

I didn't test this, but maybe it gets you started?

**Comment by moovida** [comment]
Thanks a lot for your explanations @ctrueden . I now understand.

Just to answer your question. I would like to use jupyter to teach students with 0 experience some scripting (groovy). I know they will have python with installed and when I tried to install conda on top of it, the (for me typical python) nightmare started. Jupyter didn't even start anymore complaining about missing packages that were installed. 
Since I do not have time for complex installations with the students (who nowadays have windows/macos/linux), I tried to stay with pip. But Beakerx installed with pip didn't work for me. But based on your answer I will try a few more things, or else will think about docker... even if that is not exactly my favorite solution.

Again, thanks a lot for your time to answer.

**Comment by ctrueden** [comment]
@moovida Yeah, I agree that the situation with conda is unfortunate—great idea in theory, but some problems in practice. Pip is super fast and super convenient. Too bad about plain BeakerX not working well from pip. Note that SJJK is built on top of BeakerX (in case that wasn't already clear), so it might inherit similar problems, I'm not sure.

Good luck sorting out a usable solution for the students. If you end up with e.g. a shell script to make things easy, and want to submit a PR here, I would merge it.

**Comment by ctrueden** [comment]
There is now a kernel [IJava](https://github.com/SpencerPark/IJava) that is built on JShell.
